// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlcewgljfmyydjlwekeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sY2V3Z2xqZm15eWRqbHdla2VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MTkzMDcsImV4cCI6MjA2NzA5NTMwN30.U4Nf5yjoygupdesCTJWvag2ds6wSaQhEH9YMJhEIcUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});